import { useMemo, useState } from 'react'
import PageHeader from '@/components/layout/PageHeader'
import FilterBar from '@/components/ui/FilterBar'
import { RecommendationCard } from '@/components/ui/InsightCard'
import { RECOMMENDATIONS } from '@/data/mockData'

const AREAS = ['Menu', 'Customers', 'Pricing', 'Promotions', 'Inventory']

export default function Recommendations() {
  const [filters, setFilters] = useState<Record<string, string>>({ area: 'all' })
  const rows = useMemo(
    () => RECOMMENDATIONS.filter((r) => filters.area === 'all' || r.area === filters.area),
    [filters],
  )

  return (
    <>
      <PageHeader
        title="Recommendations"
        subtitle="Prioritized actions generated by the DineIQ intelligence layer"
        demo
        actions={<span className="badge badge-violet">Demo / Mock Data</span>}
      />

      <div className="mb-5">
        <FilterBar
          filters={[{ key: 'area', label: 'Area', options: AREAS.map((a) => ({ label: a, value: a })) }]}
          values={filters}
          onChange={(k, v) => setFilters((f) => ({ ...f, [k]: v }))}
          onReset={() => setFilters({ area: 'all' })}
        />
      </div>

      <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">
        {rows.map((r, i) => (
          <RecommendationCard
            key={r.id}
            area={r.area}
            title={r.title}
            detail={r.detail}
            impact={r.impact}
            confidence={r.confidence}
            delay={(i % 3) * 70}
          />
        ))}
      </div>

      {rows.length === 0 && (
        <div className="card p-10 text-center text-sm text-ink-400">No recommendations in this area right now.</div>
      )}
    </>
  )
}
